import { cn } from '@/lib/utils';
import {
    Activity,
    AlertCircle,
    AlertTriangle,
    Archive,
    Ban,
    Banknote,
    BarChart3,
    Badge,
    BadgeCheck,
    Bell,
    Bot,
    Building2,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleDollarSign,
    CircleHelp,
    CircleOff,
    CirclePlus,
    ClipboardCheck,
    Clock,
    Contact,
    Copy,
    CornerDownRight,
    Database,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileDown,
    FileText,
    Filter,
    Folder,
    FolderOpen,
    Gem,
    GitBranch,
    GripVertical,
    History,
    Home,
    Hourglass,
    Image,
    Info,
    KeyRound,
    Landmark,
    LandPlot,
    Link,
    Link2Off,
    ListFilter,
    LoaderCircle,
    Lock,
    LockOpen,
    LogIn,
    LogOut,
    Mail,
    Menu,
    MessageSquare,
    Mic,
    MoreHorizontal,
    NotebookPen,
    Palette,
    Pencil,
    Phone,
    PiggyBank,
    Pin,
    Plus,
    Printer,
    Receipt,
    ReceiptText,
    RefreshCw,
    Ruler,
    Search,
    SearchX,
    Send,
    Settings,
    ShieldCheck,
    SquarePen,
    Star,
    StickyNote,
    Tag,
    Trash2,
    Upload,
    User,
    UserCheck,
    UserCog,
    UserPlus,
    UserSearch,
    Users,
    WalletCards,
    X,
    type LucideIcon,
} from 'lucide-react';

interface MaterialIconProps {
    name: string;
    className?: string;
    filled?: boolean;
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';
}

const sizeMap = {
    xs: 14,
    sm: 18,
    md: 20,
    lg: 24,
    xl: 28,
    '2xl': 32,
    '3xl': 36,
};

const iconMap: Record<string, LucideIcon> = {
    account_balance: Landmark,
    account_balance_wallet: WalletCards,
    account_tree: GitBranch,
    add: Plus,
    add_circle: CirclePlus,
    admin_panel_settings: ShieldCheck,
    apartment: Building2,
    arrow_back: ChevronLeft,
    arrow_downward: ChevronDown,
    arrow_forward: ChevronRight,
    arrow_upward: ChevronUp,
    badge: Badge,
    block: Ban,
    call: Phone,
    check: Check,
    check_circle: CheckCircle2,
    chevron_left: ChevronLeft,
    chevron_right: ChevronRight,
    close: X,
    contacts: Contact,
    content_copy: Copy,
    currency_exchange: CircleDollarSign,
    dashboard: BarChart3,
    database_off: Database,
    delete: Trash2,
    delete_outline: Trash2,
    diamond: Gem,
    do_not_disturb_on: CircleOff,
    download: Download,
    download_for_offline: Download,
    drag_indicator: GripVertical,
    edit: Pencil,
    edit_note: NotebookPen,
    edit_square: SquarePen,
    error: AlertCircle,
    error_outline: AlertCircle,
    expand_less: ChevronUp,
    expand_more: ChevronDown,
    fact_check: ClipboardCheck,
    file_download: FileDown,
    filter_alt: Filter,
    filter_list: ListFilter,
    folder: Folder,
    folder_managed: FolderOpen,
    folder_open: FolderOpen,
    group: Users,
    groups: Users,
    groups_2: Users,
    history: History,
    history_edu: History,
    history_toggle_off: History,
    home: Home,
    hourglass_top: Hourglass,
    how_to_reg: UserCheck,
    image: Image,
    info: Info,
    inventory_2: Archive,
    label: Tag,
    landscape: LandPlot,
    light_mode: CircleHelp,
    link: Link,
    link_off: Link2Off,
    lock: Lock,
    lock_open: LockOpen,
    lock_reset: KeyRound,
    login: LogIn,
    logout: LogOut,
    mail: Mail,
    manage_accounts: UserCog,
    menu: Menu,
    mic: Mic,
    monitoring: BarChart3,
    more_horiz: MoreHorizontal,
    notifications: Bell,
    open_in_new: ExternalLink,
    palette: Palette,
    payments: Banknote,
    person: User,
    person_add: UserPlus,
    person_search: UserSearch,
    phone: Phone,
    picture_as_pdf: FileText,
    portrait: FileText,
    print: Printer,
    progress_activity: LoaderCircle,
    push_pin: Pin,
    receipt: Receipt,
    receipt_long: ReceiptText,
    refresh: RefreshCw,
    savings: PiggyBank,
    schedule: Clock,
    search: Search,
    search_off: SearchX,
    send: Send,
    settings: Settings,
    smart_toy: Bot,
    sms: MessageSquare,
    star: Star,
    sticky_note_2: StickyNote,
    straighten: Ruler,
    subdirectory_arrow_right: CornerDownRight,
    sync: RefreshCw,
    tag: Tag,
    timeline: Activity,
    update: RefreshCw,
    upload: Upload,
    upload_file: Upload,
    verified: BadgeCheck,
    verified_user: ShieldCheck,
    visibility: Eye,
    visibility_off: EyeOff,
    warning: AlertTriangle,
    description: File,
};

export function MaterialIcon({
    name,
    className,
    filled = false,
    size = 'md'
}: MaterialIconProps) {
    const Icon = iconMap[name] || CircleHelp;

    return (
        <Icon
            aria-hidden="true"
            className={cn(
                'inline-block shrink-0 select-none text-current',
                name === 'progress_activity' && 'animate-spin',
                className
            )}
            fill={filled ? 'currentColor' : 'none'}
            size={sizeMap[size]}
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
        />
    );
}

// Common icon name mappings for easy reference
export const Icons = {
    // Navigation
    home: 'home',
    dashboard: 'dashboard',
    menu: 'menu',
    close: 'close',
    arrowBack: 'arrow_back',
    arrowForward: 'arrow_forward',
    chevronLeft: 'chevron_left',
    chevronRight: 'chevron_right',
    chevronDown: 'expand_more',
    chevronUp: 'expand_less',

    // Actions
    add: 'add',
    edit: 'edit',
    delete: 'delete',
    save: 'save',
    search: 'search',
    filter: 'filter_list',
    sort: 'sort',
    refresh: 'refresh',
    download: 'download',
    upload: 'upload',
    print: 'print',
    share: 'share',
    copy: 'content_copy',

    // User & Auth
    person: 'person',
    people: 'people',
    group: 'group',
    lock: 'lock',
    unlock: 'lock_open',
    visibility: 'visibility',
    visibilityOff: 'visibility_off',
    login: 'login',
    logout: 'logout',

    // Communication
    phone: 'phone',
    email: 'email',
    mail: 'mail',
    message: 'message',
    chat: 'chat',
    sms: 'sms',
    call: 'call',
    contactPage: 'contact_page',
    contacts: 'contacts',

    // Business
    apartment: 'apartment',
    domain: 'domain',
    business: 'business',
    payments: 'payments',
    accountBalance: 'account_balance',
    creditCard: 'credit_card',
    receipt: 'receipt',
    invoice: 'receipt_long',

    // Status
    check: 'check',
    checkCircle: 'check_circle',
    error: 'error',
    warning: 'warning',
    info: 'info',
    help: 'help',

    // Calendar & Time
    calendar: 'calendar_today',
    calendarMonth: 'calendar_month',
    schedule: 'schedule',
    event: 'event',

    // Files & Documents
    folder: 'folder',
    file: 'description',
    attachment: 'attachment',
    pdf: 'picture_as_pdf',

    // Charts & Analytics
    chart: 'bar_chart',
    pieChart: 'pie_chart',
    trending: 'trending_up',
    trendingDown: 'trending_down',
    analytics: 'analytics',

    // Settings
    settings: 'settings',
    tune: 'tune',

    // Theme
    lightMode: 'light_mode',
    darkMode: 'dark_mode',

    // Notifications
    notifications: 'notifications',
    notificationsActive: 'notifications_active',

    // Misc
    star: 'star',
    favorite: 'favorite',
    bookmark: 'bookmark',
    label: 'label',
    tag: 'sell',
    location: 'location_on',
    history: 'history',
    timeline: 'timeline',
} as const;
